/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_screen_live_Rtmp */

#ifndef _Included_com_wind_ndk_screen_live_Rtmp
#define _Included_com_wind_ndk_screen_live_Rtmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_screen_live_Rtmp
 * Method:    connect
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wind_ndk_screen_live_Rtmp_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wind_ndk_screen_live_Rtmp
 * Method:    sendData
 * Signature: ([BIIJ)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_screen_live_Rtmp_sendData
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong);

JNIEXPORT void JNICALL Java_com_wind_ndk_screen_live_Rtmp_disconnect
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
